spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: vish@post
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
